import Head from 'next/head'

import styles from '../styles/Home.module.scss'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

     <section className={styles.banner}>
       <h1 className={styles.h1}>Conheça  Nossos  Personagens</h1>
     </section>
    
    </>
  )
}
