import Head from "next/head";
import { Carousel } from "../components/Carousel";

import styles from "../styles/Home.module.scss";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          type="text/css"
          charset="UTF-8"
          href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick.min.css"
        />
        <link
          rel="stylesheet"
          type="text/css"
          href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick-theme.min.css"
        />
      </Head>

      <section className={styles.banner}>
        <div className="container">
          <h1 className={styles.h1}>Conheça Nossos Personagens</h1>
        </div>
      </section>

      <section className={styles.section}>
        <div className="container">
         

          <Carousel />
        </div>
      </section>

      <section className={styles.section}></section>
    </>
  );
}
