import Head from "next/head";
import { useEffect, useState } from "react";
import { Carousel } from "../components/Carousel";
import { GET_CHARACTERS, GET_CHARACTERS_OFFSET } from "../api";

import styles from "../styles/Home.module.scss";
import { CardPersonagem } from "../components/CardPersonagem";

export default function Home() {
  const [characters, setCharacters] = useState({});
  const [pageSelected, setPageSelected] = useState(1);
  const [pages, setPages] = useState([]);
 

  const renderPagination = (numberOfPages) => {
    if (numberOfPages > 0) {
      const arrayPages = [];
      for (let i = 1; i <= numberOfPages; i++) {
        arrayPages.push(i);
      }
      setPages(arrayPages);
    }
  };

  const getCharactersByPage = (number) => {
    let offset;

    setPageSelected(number);

    if (number === 1) {
      offset = 0;
    }

    if (number !== 1) {
      offset = 20 * (number - 1) + (number - 2);
    }

    GET_CHARACTERS_OFFSET(offset).then((response) => setCharacters(response));
  };

  useEffect(() => {
    const getCharacters = () => {
      GET_CHARACTERS().then((response) => {
        setCharacters(response);
        let numberPages = Math.ceil(response.total / response.limit)
        renderPagination(numberPages);
      });
    };

    getCharacters();
  }, []);

 

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          type="text/css"
          charset="UTF-8"
          href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick.min.css"
        />
        <link
          rel="stylesheet"
          type="text/css"
          href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick-theme.min.css"
        />
      </Head>

      <section className={styles.banner}>
        <div className="container">
          <h1 className={styles.h1}>Conheça Nossos Personagens</h1>
        </div>
      </section>

      <section className={styles.section}>
        <div className="container">
          <Carousel />
        </div>
      </section>

      <section className={`${styles.section} ${styles.sectionWhite}`}>
        <div className="container">
          <h2 className="h2Black">Lista de Personagens da Marvel</h2>

          {characters && characters.results && (
            <>
              <div className={styles.characterWrapper}>
                {characters.results.map((character) => (
                  <CardPersonagem
                    key={character.id}
                    nome={character.name}
                    foto={character.thumbnail.path}
                  />
                ))}
              </div>

              <div className={styles.pagesWrapper}>
                {
                  pages.map((page) => (
                    <span
                      onClick={() => getCharactersByPage(page)}
                      className={`${styles.pages} ${
                        pageSelected === page ? styles.pageSelected : ""
                      }`}
                      key={page}
                    >
                      {page}
                    </span>
                  ))}
              </div>
            </>
          )}
        </div>
      </section>
    </>
  );
}
